apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb
spec:
  storageClassName: local-path
  volumeMode: Filesystem
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/influxdb/